Footer
hapo-anhnd/hapo_learning pull request #1
Opened 2020-07-17 03:52 UTC by hapo-anhnd

2020-07-17 07:10 UTC, hapo-hieupm requested changes

2020-07-17 07:10 UTC, hapo-hieupm commented on css/css.css
> +    padding-top: 65px;
dùng align-items và align-content

2020-07-17 07:10 UTC, hapo-hieupm commented on index.html
> +    <section class="footer flex-column">
tại sao không dùng thẻ footer

2020-07-20 02:46 UTC, hapo-anhnd commented on index.html
> +    <section class="footer flex-column">
dùng j cũng được mak bạn.

2020-07-20 02:47 UTC, hapo-anhnd commented on css/css.css
> +    padding-top: 65px;
Okie ông

2020-07-20 06:15 UTC, hapo-hieupm approved these changes
LGTM

2020-07-20 08:47 UTC, hapo-hungnn97 approved these changes

2020-07-22 01:41 UTC, closed without merging