Header +banner
hapo-anhnd/hapo_learning pull request #2
Opened 2020-07-17 03:52 UTC by hapo-anhnd

2020-07-17 06:21 UTC, hapo-hieupm requested changes

2020-07-17 06:21 UTC, hapo-hieupm commented on index.html
>  </html>
Thêm xuống dòng nữa. Thêm theo quy tắc

2020-07-17 06:26 UTC, hapo-hieupm requested changes

2020-07-17 06:26 UTC, hapo-hieupm commented on css/css.css
>  }
Thêm xuống dòng nữa. Thêm theo quy tắc

2020-07-17 06:26 UTC, hapo-hieupm commented on css/css.css
>      left: 1088px;
Tại sao lại set 3 giá trị này nhiều lần vậy

2020-07-17 06:26 UTC, hapo-hieupm commented on css/css.css
> +    text-decoration: none;
giá trị mạc định tại sao phải khai báo

2020-07-17 06:33 UTC, hapo-hieupm commented on css/css.css
>      font-weight: normal;
Tại sao lại khai báo những thuộc tính này 2 lần

2020-07-17 06:33 UTC, hapo-hieupm commented on css/css.css
>      left: 1112px;
Khai báo thuộc tính 2 lần

2020-07-17 07:23 UTC, hapo-hungnn97 commented on css/css.css
>      font-weight: 600;
2 space

2020-07-17 07:23 UTC, hapo-hungnn97 commented on css/css.css
>      font-style: normal;
thừa

2020-07-20 02:19 UTC, hapo-anhnd commented on css/css.css
>      font-style: normal;
đã sửa

2020-07-20 02:20 UTC, hapo-anhnd commented on css/css.css
>      font-weight: 600;
đã sửa và h up lên đây

2020-07-20 02:33 UTC, hapo-anhnd commented on css/css.css
>  }
Đã thêm

2020-07-20 02:39 UTC, hapo-anhnd commented on css/css.css
>      left: 1088px;
mới sửa lại, reveiw lại hộ mình nhé

2020-07-20 02:41 UTC, hapo-anhnd commented on css/css.css
> +    text-decoration: none;
k phải giá trị mặc định bạn ơi

2020-07-20 02:43 UTC, hapo-anhnd commented on css/css.css
>      font-weight: normal;
đã sửa lại

2020-07-20 03:02 UTC, hapo-datnd commented on css/css.css
>      font-family: UTM BryantLG;
Dùng [short-hand property](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties#:~:text=Shorthand%20properties%20are%20CSS%20properties,sheets%2C%20saving%20time%20and%20energy.) đi em?

2020-07-20 03:02 UTC, hapo-datnd commented on css/css.css
> +.body1::after {
chỗ này sao cần là `body1` em? @hapo-anhnd

2020-07-20 03:03 UTC, hapo-datnd commented on css/css.css
>  .banner1 {
Chỗ này cũng tương tự sao lại là `banner1` đặt là `banner` thôi ?

2020-07-20 06:04 UTC, hapo-anhnd commented on css/css.css
>      left: 1112px;
đã sửa

2020-07-20 06:05 UTC, hapo-anhnd commented on css/css.css
>      font-family: UTM BryantLG;
Vâng anh

2020-07-20 06:05 UTC, hapo-anhnd commented on css/css.css
> +.body1::after {
em đã sửa lại rồi nhé anh

2020-07-20 06:06 UTC, hapo-anhnd commented on css/css.css
>  .banner1 {
Vâng, em đã sửa lại tất cả các tên sẽ k còn 1234 j đó ạ

2020-07-20 06:17 UTC, hapo-hieupm approved these changes
LGTM

2020-07-20 07:10 UTC, hapo-hungnn97 commented on css/css.css
> +  list-style-type: none;
để ở 1 file css riêng reset-css

2020-07-20 07:10 UTC, hapo-hungnn97 commented on css/css.css
> +  list-style-type: none;
để ở 1 file css riêng reset-css

2020-07-20 07:10 UTC, hapo-hungnn97 commented on css/css.css
> +  padding-left: .5rem;
sử dụng Shorthand property

2020-07-20 07:10 UTC, hapo-hungnn97 commented on css/css.css
> +  text-decoration: none;
để ở 1 file css riêng reset-css

2020-07-20 07:10 UTC, hapo-hungnn97 commented on css/css.css
> +  text-decoration: none;
để ở 1 file css riêng reset-css

2020-07-20 07:17 UTC, hapo-anhnd commented on css/css.css
> +  list-style-type: none;
ở đây chắc chưa cần, bao h nhiều thì tạo file riêng cũng được

2020-07-20 07:18 UTC, hapo-anhnd commented on css/css.css
> +  padding-left: .5rem;
đã xong

2020-07-20 07:18 UTC, hapo-anhnd commented on css/css.css
> +  text-decoration: none;
k cần thiết bây h ông ơi

2020-07-20 08:45 UTC, hapo-hungnn97 approved these changes
LGTM

2020-07-21 07:12 UTC, hapo-datnd commented on css/css.css
> +  width: 1440px;
chỗ này sao cần dùng position với top lớn thế ko em? có cách nào khác ko ?

2020-07-21 07:13 UTC, hapo-datnd commented on css/css.css
> +  width: 1440px;
Chỗ này tương tự trên

2020-07-21 07:13 UTC, hapo-datnd commented on css/css.css
> +  top: 4754px;
Chỗ này cũng thế

2020-07-21 07:16 UTC, hapo-anhnd commented on css/css.css
> +  width: 1440px;
có anh ạ, để em sửa ạ

2020-07-22 01:36 UTC, merged